server.port=8585
spring.datasource.url=jdbc:postgresql://localhost:5432/futvolei
spring.datasource.username=postgres
spring.datasource.password=wallace
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true






