server.port=8685

spring.datasource.url=jdbc:mysql://localhost:3306/projeto_ftv?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=wallace
spring.datasource.password=Wallace@2026Mysql!


# Driver e Dialeto
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Para o Hibernate criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true





