server.port=8685

spring.datasource.url=jdbc:postgresql://localhost:5432/futvolei
spring.datasource.username=postgres
spring.datasource.password=wallace

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update





